CXX=g++
CFLAGS    = -I./include/ -Ofast -march=native -fopenmp -g
CXXFLAGS  =  -I./include/  -Ofast -std=c++17 -march=native -fopenmp -g  -no-pie   -Wnarrowing
LDFLAGS   = -Ofast -march=native -fopenmp -g -no-pie
LDFLAGS   += lib/libpng16.a lib/libz.a

OBJECTS=src/main.o src/image.o src/stencil.o

stencil: $(OBJECTS)
	$(CXX) ${CXXFLAGS}  -o bin/stencil $(OBJECTS) $(LDFLAGS)

all:	stencil

run:	all
	bin/stencil test-image.png

clean:
	rm -f $(OBJECTS) bin/stencil output.png src/*~ *~
